# Generated by Django 4.1.3 on 2022-12-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUserPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.JSONField(unique=True)),
                ('access_token', models.CharField(max_length=150)),
                ('playlist', models.JSONField()),
            ],
        ),
    ]
